[project]
name = "kafka-mcp"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "confluent-kafka>=2.13.0",
    "fastmcp>=3.0.0",
]
